title: 'WordPress II: Creating Child Themes'
description: >-

  A step beyond customizing: building your own style for your
  WordPress site.

keywords:
  - GDI
  - GDIMpls
  - Girl Develop It
  - Class
  - Awesome
  - WordPress
  - Child
  - Theme

# This is general info for GDIMpls
contact:
  name: GDI Minneapolis
  web: http://gdiminneapolis.com
  email: "minneapolis@girldevelopit.com"
  twitter: "gdimpls"
  github: "gdiminneapolis"

tweet_tags:
  - url: "https://twitter.com/search?q=%23learnWordPress&src=typd"
    text: "#learnWordPress"
    title: "Search #learnWordPress on Twitter"
  - url: "https://twitter.com/gdimpls"
    text: "@GDIMpls"
    title: "@GDIMpls on Twitter"

style: gdidefault

# This is where your slides will be found, in the _slides/ folder.
# Number them in sequence
collections:
  - slides

# Don't change these. Change values in _staging.yml and _publish.yml appropriately.
source: source
baseurl: ""
url: ""
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true
  hard_wrap: false
