title: Your Awesome Class
author: Your Name
description: |
  Your awesome class in all it's glory.
keywords:
  - GDI
  - GDIMpls
  - Girl Develop It
  - Class
  - Awesome

# This is general info for GDIMpls
contact:
  name: GDI Minneapolis
  web: http://gdiminneapolis.com
  email: "minneapolis@girldevelopit.com"
  twitter: "gdimpls"
  github: "gdiminneapolis"

# Replace <HASHTAG> with something appropriate for your course, like #LearnJS or #IntroToPython
# Replace <AUTHOR> with your twitter handle
# use other twitter tags as you'd like
tweet_tags:
  - href: "https://twitter.com/search?q=%23<HASHTAG>&src=typd"
    text: "#<HASHTAG>"
  - href: "https://twitter.com/<AUTHOR>"
    text: "@<AUTHOR>"
  - href: "https://twitter.com/gdimpls"
    text: "@GDIMpls"


# There are a handful of styles available with reveal. They can be found in the
# reveal.js/css/themes folder, and include:
#
# style: gdicool
# style: gdidefault
# style: gdilight
# style: gdisunny
# style: simple
style: gdidefault

# This is where your slides will be found, in the _slides/ folder.
# Number them in sequence
collections:
  - slides

# Don't change these. Change values in _staging.yml and _publish.yml appropriately.
source: source
reveal_path: "/reveal.js"
baseurl: ""
url: ""
